settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: torb
  path: .
  commands:
    fmt:
      status: true
    build:
      status: true
      method: make build
    run:
      status: true
      method: ./run_local.sh
  watcher:
    extensions:
    - go
    - yaml
    paths:
    - /
    ignored_paths:
    - .git
    - vendor
