version: '3'

services:
  db:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: torb
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    volumes:
    - ./data:/var/lib/mysql
    - ./log:/var/log/mysql
    - ./db/files/my.cnf:/etc/mysql/my.cnf
    ports:
    - 3306:3306
