requires 'DBIx::Sunny';
requires 'JSON::XS', '3.00';
requires 'Kossy';
requires 'Plack::Builder';
requires 'Plack::Session';
requires 'Time::Moment';

on configure => sub {
    requires 'ExtUtils::MakeMaker';
};

on test => sub {
    requires 'Test::More';
};
