---
- name: Check Installed Go
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon
  command: /home/isucon/local/go/bin/go version
  register: go_version_output
  changed_when: go_version_output is failed
  ignore_errors: true

- name: Debug go_version_output
  debug:
    var: go_version_output

- name: Install Go 1.10.3
  become: yes
  become_user: isucon
  when: go_version_output is failed or go_version_output.stdout != "go version go1.10.3 linux/amd64"
  args:
    chdir: /home/isucon
  command: |
    /home/isucon/xbuild/go-install 1.10.3 /home/isucon/local/go

- name: Add PATH for Go
  become: yes
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK go"
    dest: /home/isucon/.bash_profile
    content: |
      export PATH=/home/isucon/local/go/bin:/home/isucon/go/bin:$PATH
      export GOROOT=/home/isucon/local/go

- name: Check Installed gb
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon
  command: /home/isucon/go/bin/gb help
  register: go_gb_version_output
  changed_when: go_gb_version_output is failed
  ignore_errors: true

- name: Debug go_gb_version_output
  debug:
    var: go_gb_version_output

- name: Install gb
  become: yes
  become_user: isucon
  when: go_gb_version_output is failed
  environment:
    PATH: "/home/isucon/local/go/bin:/home/isucon/go/bin:{{ ansible_env.PATH }}"
    GOROOT: "/home/isucon/local/go"
  args:
    chdir: /home/isucon
  command:
    go get -u github.com/constabulary/gb/...
